export const WomenData = [
  {
    id: 1,
    title: "Cashmere Tank + Bag",
    image: "/img/trending-img/latest1.jpg.webp",
    price: 98.0,
    originalPrice: 120.0,
    category: "Skincare",
    type: "Moisturizer",
    size: "Medium",
    color: "Beige",
  },
  {
    id: 3,
    title: "Wool Scarf",
    image: "/img/trending-img/latest3.jpg.webp",
    price: 60.0,
    originalPrice: 85.0,
    category: "Accessories",
    type: "Scarf",
    size: "One Size",
    color: "Gray",
  },
  {
    id: 2,
    title: "Cotton Shirt",
    image: "/img/trending-img/latest2.jpg.webp",
    price: 79.0,
    originalPrice: 99.0,
    category: "Fashion",
    type: "Shirt",
    size: "Large",
    color: "White",
  },
  {
    id: 4,
    title: "Wool Scarf",
    image: "/img/trending-img/latest4.jpg.webp",
    price: 60.0,
    originalPrice: 85.0,
    category: "Accessories",
    type: "Scarf",
    size: "One Size",
    color: "Gray",
  },
  {
    id: 5,
    title: "Wool Scarf",
    image: "/img/trending-img/latest1.jpg.webp",
    price: 60.0,
    originalPrice: 85.0,
    category: "Accessories",
    type: "Scarf",
    size: "One Size",
    color: "Gray",
  },
  {
    id: 6,
    title: "Wool Scarf",
    image: "/img/trending-img/latest2.jpg.webp",
    price: 60.0,
    originalPrice: 85.0,
    category: "Accessories",
    type: "Scarf",
    size: "One Size",
    color: "Gray",
  },
];
