export const trendingData = [
  {
    id: 1,
    name: "Men's Casual Jacket",
    image: "/img/trending-img/latest1.jpg.webp",
    price: 59.99,
    originalPrice: 80.0,
    category: "Men",
    type: "Jacket",
    size: "Large",
    color: "Navy Blue",
    brand: "Urban Luxe",
    material: "Polyester Blend",
    stock: 14,
    rating: 4.4,
    description:
      "A versatile casual jacket perfect for layering. Designed for comfort and style in any season.",
  },
  {
    id: 2,
    name: "Men's Casual Jacket",
    image: "/img/trending-img/latest2.jpg.webp",
    price: 59.99,
    originalPrice: 85.0,
    category: "Men",
    type: "Jacket",
    size: "Medium",
    color: "Black",
    brand: "Classic Wear",
    material: "Cotton Blend",
    stock: 10,
    rating: 4.2,
    description:
      "A modern casual jacket with a sleek design. Durable, comfortable, and perfect for everyday wear.",
  },
  {
    id: 3,
    name: "Men's Casual Jacket",
    image: "/img/trending-img/latest3.jpg.webp",
    price: 59.99,
    originalPrice: 90.0,
    category: "Men",
    type: "Jacket",
    size: "Small",
    color: "Gray",
    brand: "Winter Cozy",
    material: "Wool Blend",
    stock: 8,
    rating: 4.5,
    description:
      "Stylish wool blend jacket offering warmth and a refined look for casual outings.",
  },
  {
    id: 4,
    name: "Men's Casual Jacket",
    image: "/img/trending-img/latest4.jpg.webp",
    price: 59.99,
    originalPrice: 95.0,
    category: "Men",
    type: "Jacket",
    size: "Large",
    color: "Olive Green",
    brand: "Street Mode",
    material: "Polyester",
    stock: 12,
    rating: 4.6,
    description:
      "A trendy olive green jacket that blends urban style with all-day comfort.",
  },
  {
    id: 5,
    name: "Men's Casual Jacket",
    image: "/img/trending-img/latest1.jpg.webp",
    price: 59.99,
    originalPrice: 85.0,
    category: "Men",
    type: "Jacket",
    size: "Medium",
    color: "Beige",
    brand: "Urban Luxe",
    material: "Cotton",
    stock: 9,
    rating: 4.3,
    description:
      "Beige casual jacket designed for versatility. A must-have for layering and style.",
  },
  {
    id: 6,
    name: "Men's Sneakers",
    image: "/img/trending-img/latest2.jpg.webp",
    price: 89.99,
    originalPrice: 110.0,
    category: "Men",
    type: "Sneakers",
    size: "42",
    color: "White",
    brand: "StepUp",
    material: "Leather",
    stock: 16,
    rating: 4.7,
    description:
      "Premium white sneakers crafted with durable leather. Lightweight and stylish for daily wear.",
  },
  {
    id: 7,
    name: "Women's Summer Dress",
    image: "/img/trending-img/latest3.jpg.webp",
    price: 45.0,
    originalPrice: 65.0,
    category: "Women",
    type: "Dress",
    size: "Medium",
    color: "Floral Print",
    brand: "Feminine Touch",
    material: "Cotton",
    stock: 20,
    rating: 4.5,
    description:
      "Lightweight summer dress with floral design. Perfect for casual outings and warm weather.",
  },
  {
    id: 8,
    name: "Women's Handbag",
    image: "/img/trending-img/latest4.jpg.webp",
    price: 120.5,
    originalPrice: 160.0,
    category: "Women",
    type: "Handbag",
    size: "Medium",
    color: "Brown",
    brand: "Luxury Tote",
    material: "Genuine Leather",
    stock: 7,
    rating: 4.8,
    description:
      "Premium leather handbag with a sleek finish. Spacious and elegant for all occasions.",
  },
  {
    id: 9,
    name: "Baby Onesie",
    image: "/img/trending-img/latest1.jpg.webp",
    price: 25.0,
    originalPrice: 35.0,
    category: "Baby",
    type: "Onesie",
    size: "0-6 months",
    color: "Light Blue",
    brand: "Baby Bliss",
    material: "Organic Cotton",
    stock: 30,
    rating: 4.9,
    description:
      "Soft and breathable organic cotton onesie designed for your baby's comfort and safety.",
  },
  {
    id: 10,
    name: "Baby Shoes",
    image: "/img/trending-img/latest2.jpg.webp",
    price: 19.99,
    originalPrice: 28.0,
    category: "Baby",
    type: "Shoes",
    size: "0-6 months",
    color: "White",
    brand: "Tiny Steps",
    material: "Soft Fabric",
    stock: 25,
    rating: 4.7,
    description:
      "Lightweight baby shoes with soft soles. Gentle on delicate feet and perfect for first steps.",
  },
  {
    id: 11,
    name: "Trendy Sunglasses",
    image: "/img/trending-img/latest3.jpg.webp",
    price: 30.0,
    originalPrice: 45.0,
    category: "Fashion",
    type: "Sunglasses",
    size: "One Size",
    color: "Black",
    brand: "VisionPro",
    material: "Polycarbonate",
    stock: 18,
    rating: 4.6,
    description:
      "UV-protected sunglasses with a trendy frame design. Perfect accessory for summer style.",
  },
  {
    id: 12,
    name: "Classic Watch",
    image: "/img/trending-img/latest4.jpg.webp",
    price: 150.0,
    originalPrice: 200.0,
    category: "Fashion",
    type: "Watch",
    size: "Standard",
    color: "Silver",
    brand: "TimeMaster",
    material: "Stainless Steel",
    stock: 6,
    rating: 4.9,
    description:
      "Elegant stainless steel classic watch with timeless design. Durable and perfect for formal looks.",
  },
];
