export const BabyProducts = [
  {
    id: 1,
    title: "Cashmere Baby Blanket",
    image: "/img/trending-img/latest1.jpg.webp",
    price: 98.0,
    originalPrice: 120.0,
    category: "Skincare",
    type: "Blanket",
    size: "Medium",
    color: "Beige",
    brand: "SoftNest",
    material: "Cashmere Blend",
    stock: 20,
    rating: 4.8,
    description:
      "Luxuriously soft cashmere baby blanket designed to keep your little one warm and cozy. Gentle on sensitive skin.",
  },
  {
    id: 2,
    title: "Cotton Baby Shirt",
    image: "/img/trending-img/latest2.jpg.webp",
    price: 79.0,
    originalPrice: 99.0,
    category: "Fashion",
    type: "Shirt",
    size: "Large",
    color: "White",
    brand: "TinyTrend",
    material: "100% Organic Cotton",
    stock: 18,
    rating: 4.6,
    description:
      "Soft and breathable cotton shirt for babies. Perfect for playtime and daily wear, ensuring comfort throughout the day.",
  },
  {
    id: 3,
    title: "Wool Baby Scarf",
    image: "/img/trending-img/latest3.jpg.webp",
    price: 60.0,
    originalPrice: 85.0,
    category: "Accessories",
    type: "Scarf",
    size: "One Size",
    color: "Gray",
    brand: "WarmHug",
    material: "Pure Wool",
    stock: 15,
    rating: 4.7,
    description:
      "Soft wool baby scarf to keep your child warm during winters. Lightweight and safe for sensitive skin.",
  },
  {
    id: 4,
    title: "Knitted Baby Scarf",
    image: "/img/trending-img/latest4.jpg.webp",
    price: 60.0,
    originalPrice: 85.0,
    category: "Accessories",
    type: "Scarf",
    size: "One Size",
    color: "Gray",
    brand: "BabyWarm",
    material: "Wool Blend",
    stock: 12,
    rating: 4.5,
    description:
      "Hand-knitted baby scarf designed with love. Provides warmth and adds a cute touch to baby outfits.",
  },
  {
    id: 5,
    title: "Fleece Baby Scarf",
    image: "/img/trending-img/latest1.jpg.webp",
    price: 60.0,
    originalPrice: 85.0,
    category: "Accessories",
    type: "Scarf",
    size: "One Size",
    color: "Gray",
    brand: "CozyKid",
    material: "Soft Fleece",
    stock: 14,
    rating: 4.4,
    description:
      "Lightweight fleece baby scarf that provides extra warmth without irritation. Designed for all-day comfort.",
  },
  {
    id: 6,
    title: "Wool Baby Wrap",
    image: "/img/trending-img/latest2.jpg.webp",
    price: 60.0,
    originalPrice: 85.0,
    category: "Accessories",
    type: "Wrap",
    size: "One Size",
    color: "Gray",
    brand: "LittleSnug",
    material: "Pure Wool",
    stock: 10,
    rating: 4.3,
    description:
      "A warm and stylish wool baby wrap. Perfect for outdoor strolls, keeping babies cozy and secure.",
  },
];
